### ISSUE TITLE
Test fails `Parse_UnknownProjectSettingClause_With_Composed_Setting_Keyword_Value` with unique value

### ISSUE THREAD

**Issue by Catalin-Andronie** [Catalin-Andronie/dbml.net#73]
```log
[xUnit.net 00:00:01.12]     DbmlNet.Tests.Unit.CodeAnalysis.Syntax.ParserTests.Parse_UnknownProjectSettingClause_With_Composed_Setting_Keyword_Value(settingValueKind: UniqueKeyword, settingValueText: "unique", settingValue: null) [FAIL]
  Failed DbmlNet.Tests.Unit.CodeAnalysis.Syntax.ParserTests.Parse_UnknownProjectSettingClause_With_Composed_Setting_Keyword_Value(settingValueKind: UniqueKeyword, settingValueText: "unique", settingValue: null) [2 ms]
  Error Message:
   Assert.Equal() Failure: Strings differ
                                     (pos 25)
Expected: "Unknown project setting 'Ref'."
Actual:   "Unknown project setting 'ref'."
                                     (pos 25)
  Stack Trace:
     at DbmlNet.Tests.Unit.CodeAnalysis.Syntax.ParserTests.AssertDiagnostics(String[] expectedMessages, ImmutableArray`1 diagnostics) in D:\The-ACN-Man\dbml.net\tests\DbmlNet.Tests.Unit\CodeAnalysis\Syntax\ParserTests.cs:line 85
   at DbmlNet.Tests.Unit.CodeAnalysis.Syntax.ParserTests.ParseMember(String text, String[] diagnosticMessages) in D:\The-ACN-Man\dbml.net\tests\DbmlNet.Tests.Unit\CodeAnalysis\Syntax\ParserTests.cs:line 28
   at DbmlNet.Tests.Unit.CodeAnalysis.Syntax.ParserTests.ParseProjectSettingListClause(String text, String[] diagnosticMessages) in D:\The-ACN-Man\dbml.net\tests\DbmlNet.Tests.Unit\CodeAnalysis\Syntax\ParserTests.cs:line 149
   at DbmlNet.Tests.Unit.CodeAnalysis.Syntax.ParserTests.Parse_UnknownProjectSettingClause_With_Composed_Setting_Keyword_Value(SyntaxKind settingValueKind, String settingValueText, Object settingValue) in D:\The-ACN-Man\dbml.net\tests\DbmlNet.Tests.Unit\CodeAnalysis\Syntax\ParserTests.ProjectSettingClause.cs:line 288
   at InvokeStub_ParserTests.Parse_UnknownProjectSettingClause_With_Composed_Setting_Keyword_Value(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

![image](https://github.com/Catalin-Andronie/dbml.net/assets/10738038/6bcb81e1-f92b-4c76-bd36-5e31cd24f454)

**Comment by Catalin-Andronie** [comment]
This should not happen anymore since we parse `Ref ` and `ref` as the same keyword.
